[package]
name = "rust_tokio_yahoo_stock_data"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
csv = "1.3.0"
thirtyfour = "0.32.0"
tokio = { version = "1.37.0", features = ["full"] }
